permalink: '/:title/'
snipcart_js: 'https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.js'
snipcart_css: 'https://cdn.snipcart.com/themes/v3.0.4/default/snipcart.css'
logos:
  light:
    optimized: /images/namething.png
    fallback: ''
  dark:
    optimized: ''
    fallback: ''
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
collections:
  posts:
    permalink: '/posts/:title/'
baseurl: /
title: Snipcart
snipcart_api_key: ''
palette: default
palettes:
  default:
    sass:
      default: '#FFFFFF'
      bg_image_cart_fallback: /images/header.jpg
      bg_image_cart_optimized: /images/cart-bg.webp
      active: '#88DD9B'
      light_grey: '#6B797A'
      dark_grey: '#273132'
      bg_image_secondary_fallback: /images/leaf-light-grey.svg
      bg_image_primary_optimized: /images/header.webp
      active_medium: '#5C9174'
      active_dark: '#547567'
      bg_image_product_fallback: /images/leaf.svg
      medium: '#6B797A'
      light: '#F0F0F0'
      dark: '#384647'
      bg_image_product_optimized: /images/leaf.svg
      bg_image_primary_fallback: /images/header.jpg
      active_light: '#C0FDB6'
      bg_image_secondary_optimized: /images/leaf-light-grey.svg
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
